# Generated by Django 3.2.12 on 2022-02-11 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_blogindexpage_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogindexpage',
            name='body',
        ),
        migrations.AddField(
            model_name='blogpage',
            name='displayTitle',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
