# Generated by Django 3.2.12 on 2022-02-11 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20220211_2228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='displayTitle',
        ),
        migrations.AddField(
            model_name='blogindexpage',
            name='displayTitle',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
