# Generated by Django 3.2.12 on 2022-02-21 22:19

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20220211_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='hero',
            field=models.BooleanField(blank=True, default=False, help_text='Is this a hero post?'),
        ),
        migrations.AlterField(
            model_name='blogpagetag',
            name='content_object',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='blog.blogpage'),
        ),
    ]
