# Generated by Django 3.2.12 on 2022-02-10 17:26

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_homepage_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='body',
            new_name='titleText',
        ),
        migrations.AddField(
            model_name='homepage',
            name='bodyText',
            field=wagtail.core.fields.StreamField([('body', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.CharBlock(help_text='Body text to display', required=True))]))], blank=True, null=True),
        ),
    ]
