# Generated by Django 3.2.12 on 2022-02-10 17:28

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20220210_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='bodyText',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='titleText',
        ),
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.core.fields.StreamField([('title', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.CharBlock(help_text='Title text to display', required=True))]))], blank=True, null=True),
        ),
    ]
